# Generated by Django 4.2.5 on 2024-03-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManagementSystem_app', '0002_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
